// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbmjikjmrjxybzzqmjvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibWppa2ptcmp4eWJ6enFtanZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDg5OTIsImV4cCI6MjA3MTM4NDk5Mn0._kVBO8ZpKUY3QXD3S-FESnqM8ti-0svCRgp8bVcr6GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});